Repository hoprnet/hoprd-operator, pull requests merged in 2023-03, with the labels that each got.

#16 Include secret management on Operator
  .gitignore
  Cargo.lock
  Cargo.toml
  Dockerfile
  Makefile
  README.md
  charts/hoprd-operator/Chart.lock
  charts/hoprd-operator/Chart.yaml
  charts/hoprd-operator/README.md
  charts/hoprd-operator/templates/configmap.yaml
  charts/hoprd-operator/templates/crd.yaml
  charts/hoprd-operator/templates/deployment.yaml
  charts/hoprd-operator/templates/persistence-volume-claim.yaml
  charts/hoprd-operator/templates/rbac.yaml
  charts/hoprd-operator/values.yaml
  hoprd-node-1.yaml
  sample_secret_content.json
  src/actions.rs
  src/constants.rs
  src/crd.rs
  src/hoprd_deployment.rs
  src/hoprd_hoprd.rs
  src/hoprd_jobs.rs
  src/hoprd_secret.rs
  src/hoprd_service.rs
  src/hoprd_service_monitor.rs
  src/main.rs
  src/operator.rs
  src/utils.rs
Labels: enhancement, devops

#17 Install Admin UI as part of the operator
  .github/workflows/container-master.yml
  .github/workflows/container-pr.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  charts/hoprd-operator/Chart.yaml
  charts/hoprd-operator/README.md
  charts/hoprd-operator/templates/_helpers.tpl
  charts/hoprd-operator/templates/configmap-config.yaml
  charts/hoprd-operator/templates/configmap-scripts.yaml
  charts/hoprd-operator/templates/crd.yaml
  charts/hoprd-operator/templates/deployment-adminui.yaml
  charts/hoprd-operator/templates/deployment-operator.yaml
  charts/hoprd-operator/templates/deployment.yaml
  charts/hoprd-operator/templates/ingress.yaml
  charts/hoprd-operator/templates/persistence-volume-claim.yaml
  charts/hoprd-operator/templates/rbac.yaml
  charts/hoprd-operator/templates/secret.yaml
  charts/hoprd-operator/templates/service.yaml
  charts/hoprd-operator/values.yaml
  hoprd-node-1.yaml
  sample_config.yaml
  src/actions.rs
  src/constants.rs
  src/hoprd_deployment.rs
  src/hoprd_hoprd.rs
  src/hoprd_ingress.rs
  src/hoprd_jobs.rs
  src/hoprd_secret.rs
  src/hoprd_service_monitor.rs
  src/main.rs
  src/model.rs
  src/operator.rs
  src/utils.rs
Labels: enhancement, devops

#29 Bump rust base image to version 1.68
  Cargo.lock
  Cargo.toml
  Dockerfile
  charts/hoprd-operator/Chart.yaml
Labels: enhancement

#35 Fixing SecretKeyName by SecretName
  charts/hoprd-operator/Chart.yaml
  charts/hoprd-operator/templates/deployment-operator.yaml
Labels: bug, devops

#36 Add deletion permissions
  charts/hoprd-operator/Chart.yaml
  charts/hoprd-operator/templates/rbac.yaml
Labels: bug, devops

#37 Owned references
  Cargo.lock
  Cargo.toml
  Makefile
  charts/hoprd-operator/Chart.yaml
  charts/hoprd-operator/README.md
  charts/hoprd-operator/templates/NOTES.txt
  charts/hoprd-operator/templates/configmap-config.yaml
  charts/hoprd-operator/templates/configmap-scripts.yaml
  charts/hoprd-operator/templates/deployment-adminui.yaml
  charts/hoprd-operator/templates/deployment-operator.yaml
  charts/hoprd-operator/values.yaml
  hoprd-node-1.yaml
  sample_config.yaml
  src/constants.rs
  src/controller.rs
  src/hoprd.rs
  src/hoprd_deployment.rs
  src/hoprd_ingress.rs
  src/hoprd_jobs.rs
  src/hoprd_secret.rs
  src/hoprd_service.rs
  src/hoprd_service_monitor.rs
  src/model.rs
  src/servicemonitor.rs
  src/utils.rs
Labels: enhancement, devops

#41 Move ingress definition values to adminUI and log reconciliation erro…
  Cargo.lock
  Cargo.toml
  Makefile
  charts/hoprd-operator/Chart.yaml
  charts/hoprd-operator/README.md
  charts/hoprd-operator/templates/configmap-config.yaml
  charts/hoprd-operator/templates/ingress.yaml
  charts/hoprd-operator/values.yaml
  src/controller.rs
Labels: bug, devops

#44 Adding more permissions
  charts/hoprd-operator/Chart.yaml
  charts/hoprd-operator/templates/rbac.yaml
Labels: bug, devops

#45 Fix the use of secretName on creating jobs
  Cargo.lock
  Cargo.toml
  Makefile
  charts/hoprd-operator/Chart.yaml
  charts/hoprd-operator/templates/configmap-config.yaml
  sample_config.yaml
  src/hoprd_jobs.rs
  src/model.rs
Labels: bug, devops
